# Generated by Django 3.1.7 on 2021-02-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='is_activated',
            field=models.BooleanField(default=True),
        ),
    ]
